
CREATE TABLE USERS(
ID SERIAL PRIMARY KEY, 
name VARCHAR(255) NOT NULL UNIQUE
);

 CREATE TABLE WORD_HISTORY(ID SERIAL, 
 word VARCHAR(255), 
 searched_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
 user_id INTEGER REFERENCES USERS(ID) ON DELETE CASCADE
 );
